Algoritmo "combinaçoes"
// 
//  
// Descrição   : combina resultados de estrutura de repeticao
// Autor(a)    : Joao paulo vaz
// Data atual  : 02/03/2023
Var
// Seção de Declarações das variáveis 

    c1 : inteiro
    c2 : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    
    para c1 := 1 ate 3 faca
      para c2 := 1 ate 3 faca
        EscrevaL(c1, c2)
      FimPara
    FimPara

Fimalgoritmo